name: Terraform Test and Docs

on:
  pull_request:
    branches: [ main ]

  # Support for running the workflow directly from the GH Actions tab.
  workflow_dispatch:

permissions:
  contents: read

jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest

    steps:
    # Setting up Terraform to use the test features
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.0

  test:
    name: test
    runs-on: ubuntu-latest
    needs: setup
    permissions:
      contents: write
    
    # Strategy to run the linting in multiple folders
    strategy:
      matrix:
        subdir: ["./terraform/backend", "./terraform/resources"]
    steps:
    - name: Check out Code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        
    # Make sure we have a consistent format between all the Terraform files
    # If your step fails here, run "terraform fmt -recursive" on the respective folder so you fix the linting issues.
    - name: Terraform Format
      id: fmt
      working-directory: "${{ matrix.subdir }}"
      run: terraform fmt -check -recursive
    
    # Make sure to init in case it is using other modules
    - name: Terraform Init
      id: init
      working-directory: "${{ matrix.subdir }}"
      run: |
        git config --global url."https://${{ secrets.GH_CROUD_PAT }}@github.com".insteadOf "ssh://git@github.com"
        terraform init -input=false -backend=false

    # Validate the Terraform templates
    - name: Terraform Validate
      id: validate
      working-directory: "${{ matrix.subdir }}"
      run: terraform validate -no-color

  # Automatic doc generation
  docs:
    name: docs
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render Terraform docs inside the DOCS.md and push changes back to PR branch
      # NOTE: RIGHT NOW (04/05/2023) THIS LIBRARY IS GENERATING A WARNING ABOUT A DEPRECATED ACTION
      # THEY HAVEN'T RELEASED A NEW VERSION THAT SOLVES THIS, BUT THEY HAVE A COMMIT THAT HAS THE FIX.
      # ORIGINAL LINE BELOW
      # uses: terraform-docs/gh-actions@v1.0.0
      uses: terraform-docs/gh-actions@18dc76d9b2e3c746cf6f8e073c7fa7df16dcf620
      with:
        # Multiple paths to add the DOCS.md to
        working-dir: terraform/backend,terraform/resources,terraform/resources/modules/workstations
        output-file: DOCS.md
        output-method: inject
        git-push: "true"
        git-commit-message: "docs: automated generation of DOCS.md"
