name: Clean Up After Bump

on:
  pull_request:
    types:
      - closed

jobs:
  delete-branch:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: "Delete Branch"
        if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'version-bump')
        run: |
          git config --local user.name github-actions[bot]
          git config --local user.email 41898282+github-actions[bot]@users.noreply.github.com
          git push origin --delete ${{ github.event.pull_request.head.ref }}